// Only for the official languages that FDM named in the project brief
const translations = {
    en: {
        available: 'Available from',
        month: 'month',
        bath: 'Bath',
        bed: 'Bed',
        livRoom: 'Living Room',
        desc: 'Description',
        features: 'Features',
        accessibility: 'Accessibility',
        rating: 'Rating',
        wifi: 'Wifi',
        location: 'Location',
        cleanliness: 'Cleanliness',
        posted: 'Posted By',
        message: 'Message',
        translate: 'Translate',
        loadingAccom: 'Loading Accommodation...',
        share: 'Share',
    },
    fr: {
        available: 'Disponible à partir de',
        month: 'mois',
        bath: 'Bain',
        bed: 'Lit',
        desc: 'Description',
        livRoom: 'Salon',
        features: 'Caractéristiques',
        accessibility: 'Accessibilité',
        rating: 'Evaluation',
        wifi: 'Wifi',
        location: 'Emplacement',
        cleanliness: 'Propreté',
        posted: 'Publié par',
        message: 'Envoyer un message',
        translate: 'Traduire',
        loadingAccom: 'Chargement les hébergements...',
        share: 'Partager',
    },
    de: {
        available: 'Verfügbar seit',
        month: 'Monat',
        bath: 'Bad',
        bed: 'Bett',
        desc: 'Beschreibung',
        livRoom: 'Wohnzimmer',
        features: 'Funktionen',
        accessibility: 'Zugänglichkeit',
        rating: 'Bewertung',
        wifi: 'WLAN',
        location: 'Lage',
        cleanliness: 'Sauberkeit',
        posted: 'Veröffentlicht von',
        message: 'Eine Nachricht senden',
        translate: 'Übersetzen',
        loadingAccom: 'Unterkünfte werden geladen...',
        share: 'Teilen',
    },
};

export { translations };
